#!/bin/sh

echo Converting codesearch...
echo `sass codesearch.scss ../chromium-dev-refresh/codesearch.css --sourcemap=none`
echo Converting crbug...
echo `sass crbug.scss ../chromium-dev-refresh/crbug.css --sourcemap=none`
echo Converting codereview...
echo `sass codereview.scss ../chromium-dev-refresh/codereview.css --sourcemap=none`
echo Converting gitblame...
echo `sass gitblame.scss ../chromium-dev-refresh/gitblame.css --sourcemap=none`

echo Done.
